### ISSUE TITLE
Node missing parent attribute (onNodeClick callback) in v2.x

### ISSUE THREAD

**Issue by Joroze** [bkrem/react-d3-tree#349] opened 2021-06-11 04:12 UTC
## Are you reporting a bug, or opening a feature request?
Bug
  
## What is the actual behavior/output?
In version 1.x, the node object that the onClick callback function has contains a "parent" attribute. onNodeClick seems to replace onClick in version 2.x, but the node passed into the callback no longer contains a "parent" attribute.

## What is the behavior/output you expect?
onNodeClick should accept the selected node which contains a parent attribute pointing to its parent node (if exists)

## Can you consistently reproduce the issue/create a reproduction case (e.g. on https://codesandbox.io)?
Yes

## What version of react-d3-tree are you using?
2.x (any 2.x)

**Comment by bkrem** [comment] 2021-06-23 18:07
Hi @Joroze,

Thanks for making me aware of this, this was an unintended regression during the huge `v2` refactor. 

This is one of those refactoring slip-ups where I ask myself how I could've missed this, also because the correct implementation - aligning the type of `Node` passed to `onNode...` handlers with the ones already used by `onLink...`handlers - drastically simplifies the internal handling code 🤦 
In retrospect it seems I didn't notice how the underlying structure had subtle changes, while everything looked correct at the code level.

I'm almost done with a fix, but need to put some more due diligence into the release process, since this will need to ship as `v3.0.0`. The small change needed in the `onNode...` callback signatures in the top-level API technically makes this a breaking change.

**Comment by bkrem** [comment] 2021-06-24 16:45
Fixed in [v3.0.0](https://github.com/bkrem/react-d3-tree/releases/tag/v3.0.0).

While technically a breaking change due to the adjustment needed in the top-level API, this should be a relatively painless upgrade from v2. 

The linked release notes also contain a before/after comparison to hopefully make things easier 🤞  

Thanks again for reporting this 👍

**Closed by bkrem** 2021-06-24 16:45 UTC
Labels: bug

**Comment by Joroze** [comment] 2021-06-24 19:35
Hi @bkrem, no problem!

How would you feel about the `renderCustomNodeElement` prop callback providing the same information such as the parent attribute, so we can also implement our own custom event handling logic along with that data?

**Comment by bkrem** [comment] 2021-06-25 13:16
Additional change for `renderCustomNodeElement` shipped in [v3.1.0](https://github.com/bkrem/react-d3-tree/releases/tag/v3.1.0) 🚀 

Thanks for the contribution on this one @Joroze! 🙇
