### ISSUE TITLE
Bug: initialDepth prop rendering nodes without links

### ISSUE THREAD

**Issue by RohanDamani** [bkrem/react-d3-tree#33] opened 2017-09-28 01:23 UTC
There is a bug with the initialDepth prop.  The nodes are displaying without the links, beyond the initial depth.

`<Tree data={myTreeData} initialDepth={2} />` is rendering 

![image](https://user-images.githubusercontent.com/8662419/30945081-c5daee24-a3b0-11e7-9b26-b943eb25d5f8.png)

**Comment by bkrem** [comment] 2017-09-28 15:54
Hi @RohanDamani, 

Thank you for opening an issue, this definitely looks strange.

Could you please post what `myTreeData` looks like and/or any errors that are logged to the console?
I tried to reproduce this with the example `myTreeData` shown in the documentation but wasn't able to: https://codesandbox.io/s/nno54xywrj

If you're able to reproduce this in the sandbox or post steps on how to reproduce I'll make sure to get this fixed as soon as possible!

**Comment by RohanDamani** [comment] 2017-09-28 22:29
I've figured out what is causing it! Do you use Redux?

When dispatching an ascync action on componentDidMount or componentWillMount, as the fetch resolves, and updates the store state, it conflicts.   

Not sure why or how, but it seems like the redux update timing is overriding the process to turn the opacity of the 'closed' leaves to 0. 

I added a check to see if the results from the fetch existed, only then render the Tree, and it's working.  

Any ideas?

**Comment by bkrem** [comment] 2017-09-29 13:48
The library doesn’t use redux, just react’s `setState` and changes propagate via the components’ props.

Please post a link to your reproduction case, I have no way to test for and fix this case otherwise.

**Comment by bkrem** [comment] 2017-10-04 14:50
Closing since I can't reproduce this without a detailed description/repro link.

Feel free to open another issue with a reproduction case and I'll make sure to get it fixed :+1:

**Closed by bkrem** 2017-10-04 14:50 UTC
Labels: needs clarification

**Comment by RohanDamani** [comment] 2017-10-04 22:05
Thanks
