### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by samankhademi** [bkrem/react-d3-tree#95] opened 2018-04-17 12:18 UTC
I think that is because there is no "window" in server side rendering
i use react Starter Kit
ReferenceError: window is not defined
    at D:\project\iTask\node_modules\react-d3-tree\lib\react-d3-tree.min.js:1:5209
    at D:\project\iTask\node_modules\react-d3-tree\lib\react-d3-tree.min.js:1:5171
    at e.exports (D:\project\iTask\node_modules\react-d3-tree\lib\react-d3-tree.min.js:1:5767)
    at Object.<anonymous> (D:\project\iTask\node_modules\react-d3-tree\lib\react-d3-tree.min.js:1:22270)
    at t (D:\project\iTask\node_modules\react-d3-tree\lib\react-d3-tree.min.js:1:812)
    at Object.<anonymous> (D:\project\iTask\node_modules\react-d3-tree\lib\react-d3-tree.min.js:1:18419)
    at t (D:\project\iTask\node_modules\react-d3-tree\lib\react-d3-tree.min.js:1:812)
    at Object.e.exports (D:\project\iTask\node_modules\react-d3-tree\lib\react-d3-tree.min.js:1:7779)
    at t (D:\project\iTask\node_modules\react-d3-tree\lib\react-d3-tree.min.js:1:812)
    at Object.defineProperty.value (D:\project\iTask\node_modules\react-d3-tree\lib\react-d3-tree.min.js:1:6295)
    at t (D:\project\iTask\node_modules\react-d3-tree\lib\react-d3-tree.min.js:1:812)
    at t.exports (D:\project\iTask\node_modules\react-d3-tree\lib\react-d3-tree.min.js:1:1169)
    at D:\project\iTask\node_modules\react-d3-tree\lib\react-d3-tree.min.js:1:1178
    at n (D:\project\iTask\node_modules\react-d3-tree\lib\react-d3-tree.min.js:1:81)
    at Object.<anonymous> (D:\project\iTask\node_modules\react-d3-tree\lib\react-d3-tree.min.js:1:676)
    at Module._compile (module.js:635:30)

**Comment by bkrem** [comment] 2018-06-05 15:58
Hi @samankhademi, 

Yes, the issue here is that the library currently doesn't directly support server-side rendering. I've posted a workaround in #40 that should help you bypass the error until support for SSR has been added.

I'll close this as a duplicate of #40, but feel free to contribute inside that issue or ask any further questions you may have :)

**Closed by bkrem** 2018-06-05 15:58 UTC

**Comment by Zunaib** [comment] 2019-10-16 11:18
If anyone is still strugling ?

For Imports 
---------------
if (canUseDOM()) {
  const ReactD3Tree = require('react-d3-tree');
  Tree = ReactD3Tree.default;
}


For Usage
--------------
 if (!canUseDOM()) return null;
  return (
    <div className="react-tree" id="treeWrapper" style={{ width: '150em', height: '150em' }}>
      <Tree {...props} />
    </div>
  );

Function (canUseDOM)
------------
export function canUseDOM() {
  return !!(typeof window !== 'undefined' && window.document && window.document.createElement);
}
