### ISSUE TITLE
New data set ignores initialDepth

### ISSUE THREAD

**Issue by RohanDamani** [bkrem/react-d3-tree#47] opened 2017-10-27 23:57 UTC
If the data set changes (ie user filters), the tree rerenders with all nodes open. 

I am using a dynamic initial depth prop to maintain which level is open, and I would like the tree to reread the initial depth prop as the data set changes to stay at the current highest level open.  

As the user clicks a node, I will pass the depth to state.  In conjunction with https://github.com/bkrem/react-d3-tree/issues/46 the other nodes will close, so the clicked node will be at the highest level.  The user can filter data, and the tree will render new nodes to the same level.

**Comment by francisngo** [comment] 2019-04-15 20:34
@RohanDamani Could you paste/share your code for this?

**Comment by tokarskyibogdan** [comment] 2019-10-11 07:16
Did someone find solution? 
@francisngo steps to reproduce
- create react component with react-d3-tree element
- when the component receives a new tree data the tree is going to show every node as opened

**Comment by bkrem** [comment] 2020-01-15 15:34
Apologies it's taken me so long to address this issue properly. 

I'm dedicating myself for the next few weeks to resolving long-standing issues that are still shippable as part of v1 (like this one), as well as shipping a long-overdue v2 with a typescript-first, less opinionated, and more flexible public API.

I will update this thread once this issue is resolved for the `updating data` case, either as one of the last v1 patches, or as part of v2.

**Comment by bkrem** [comment] 2020-12-29 16:30
Fixed in v1.17.1 and by extension in [v2.0.0](https://github.com/bkrem/react-d3-tree/releases).

If you're able to, I'd highly recommend checking out [v2](https://github.com/bkrem/react-d3-tree/), since it's a major overhaul of the docs, the library's internals (Typescript-first) the API's flexibility (e.g. [`renderCustomNodeElement`](https://github.com/bkrem/react-d3-tree/#rendercustomnodeelement)).

Going forward, `v1` is considered deprecated and will only be updated for necessary patch releases. You can still find the old docs on the [`v1` branch](https://github.com/bkrem/react-d3-tree/tree/v1).

I've added regression tests for this bug, but if you do encounter it again please open another issue.

Apologies for the long wait with this annoying bug 🙏 v2 should've been done early this year, but I had to put unpaid projects (including open-source) aside for most of 2020 due to some "unexpected global events".

**Closed by bkrem** 2020-12-29 16:30 UTC
Labels: DX, bug, v2.0.0
