### ISSUE TITLE
Update the tree

### ISSUE THREAD

**Issue by caginbektas** [bkrem/react-d3-tree#283] opened 2020-03-06 15:35 UTC
## Question

Hello,

I may need to change the tree on the fly. What exactly do I need to do to change it?

The exact requirement is, the source data may change, I am able to get this change, and I want to draw the tree with the new data.

**Comment by edo** [comment] 2020-03-14 07:07
Hi @caginbektas. Your request is very vague. What is stopping you from changing it on the fly?

**Comment by bkrem** [comment] 2020-03-15 10:24
Hi @caginbektas,

As @edo mentioned, it's not really clear what exactly the issue is that you're facing. If you're simply looking to update the tree whenever your dataset changes, you need to manage the dataset as state in your `Tree`'s parent component, e.g.:

```js
const TreeContainer = () => {
  const [treeData, setTreeData] = useState([])
  
  useEffect(() => {
    // something happens that requires you to update `treeData`...
	setTreeData(nextTreeData)
  })

  return (
	<Tree data={treeData} />
  )
}
```

This (simplified) snippet is using React hooks, but it works the same if you're using classes, except you'd be passing e.g. `this.state.treeData` to `Tree` instead.

Hope that helps, I'm closing this issue for now. If the problem is more nuanced, feel free to reopen this with a more detailed description of the issue :)

**Closed by bkrem** 2020-03-15 10:24 UTC
