### ISSUE TITLE
Getting error with react-d3-tree. 

### ISSUE THREAD

**Issue by mayurrotti** [bkrem/react-d3-tree#358] opened 2021-08-05 05:25 UTC
Thank you for taking the time to report an issue with react-d3-tree!  

Feel free to delete any questions that do not apply.

## Are you reporting a bug, or opening a feature request?
is it a bug? 
![Capture](https://user-images.githubusercontent.com/81507258/128295497-2a484605-8fee-404f-9722-401ed9fbab9f.PNG)

also checked that dequal is available in the node_modules

  
## What is the actual behavior/output?
unable to render a simple tree due to the error "lite_1.dequal is not a function"

## What is the behavior/output you expect?
render a simple tree. could it be that it is an issue with existing dependencies? 

## What version of react-d3-tree are you using?
tried with version 2.0.0 and latest 3.1.1

**Comment by bkrem** [comment] 2021-08-25 14:58
Hi,

Closing since I wasn't able to reproduce this.

Seems to be a local dependency issue but please comment again here if you can consistently reproduce this on a tool like codesandbox or similar 👍

**Closed** 2021-08-25 14:58 UTC
