### ISSUE TITLE
Transform does not get applied immediately in React 15

### ISSUE THREAD

**Issue by bhgsbatista** [bkrem/react-d3-tree#240] opened 2019-09-18 17:50 UTC
## Are you reporting a bug, or opening a feature request?
Bug
  
## What is the actual behavior/output?
Translate prop does not seem translate SVG correctly until user pans the view when using React 15.

## What is the behavior/output you expect?
Translate prop would translate SVG correctly from the start.

## Can you consistently reproduce the issue/create a reproduction case (e.g. on https://codesandbox.io)?
Yes: https://codesandbox.io/s/nifty-wilson-xbfl8

## What version of react-d3-tree are you using?
1.15.1

**Comment by bhgsbatista** [comment] 2019-09-18 17:50
More info: https://github.com/bkrem/react-d3-tree/issues/237#issuecomment-532791875

**Comment by bkrem** [comment] 2019-09-18 18:19
Ugh sorry that's annoying. I've addressed what I could this evening, I'll try to patch that up tomorrow or Friday but I can't promise I'll have time to work on the repo.

If it's urgent for you please submit a PR that fixes this and I'll get it released for you.

**Comment by bhgsbatista** [comment] 2019-09-18 18:21
No worries, I am working off of my fork. It's not the best fix (since it's not compatible with React 17), but it works for now.

**Comment by bkrem** [comment] 2019-09-19 16:21
Fixed in [v1.15.2](https://github.com/bkrem/react-d3-tree/releases/tag/v1.15.2)

Sorry again for the unnecessary regression, I was rushing the compat fix because I didn't have much time to get it shipped.

(cc @ftirej)

**Closed by bkrem** 2019-09-19 16:21 UTC

**Comment by bhgsbatista** [comment] 2019-09-19 17:23
No problem, thanks for fixing it quickly and properly!
